'''
This file contains handlers for parsing the xml file generated by Koopa.
The xml tree is recursively traversed and recognized statements are processed
by their corresponding handlers, which return a structure representing the
statement and its associated data.
'''

import re

# ─────────────────────────────────────────────────────────────────────────────
#  Main processing
# ─────────────────────────────────────────────────────────────────────────────
# tags that manage their own children (if, for, while):
internal_recursion_tags = [
    "ifStatement"
]

def process_node(elem, ident=0, lines=None):
    if lines is None:
        lines = []

    handler = Handlers.get(elem.tag)
    if handler is not None:
        lines.append(handler(elem))

        if elem.tag in internal_recursion_tags:
            return lines

    for child in elem:
        process_node(child, ident + 1, lines)

    return lines


# ─────────────────────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────────────────────
# find all matching text
def extractText(elem, tag):
    return "".join(txt.text.strip()
                   for cons in elem.findall(f".//{tag}")
                   for txt in cons.findall(".//t")
                   if txt.text)

# because koopa separates letters from nums in variable names...
def extractVarNames(elem, tag):
    vars = []
    for var in elem.findall(".//cobolWord"):
        var_name = "".join(t.text for t in var.findall("t"))
        vars.append(var_name)
    return vars

def extractConditionTokens(elem):
    node = elem.find(".//condition")
    tokens = []

    cond_tokens = {
        "<"   : "slt",
        "<="  : "sle",
        ">"   : "sgt",
        ">="  : "sge",
        "="   : "eq",
        "<>"  : "ne",

        "IS"  : "is",
        "NOT" : "not",

        "AND" : "and",
        "OR"  : "or"
    }

    for child in node.iter():
        tag = child.tag

        if tag =="cobolWord":
            word = "".join(t.text for t in child.findall("t"))
            if word:
                tokens.append(word)

        elif tag == "t" and child.text.upper() in cond_tokens:
            if child.text and child.text.strip():
                '''
                If the last op was a rela op, and the current tok is also a
                rela op, then they form the same op
                (e.g. if the last was < or >, and the current is = or >,
                this forms <=, >=, or <>).
                '''
                last_tok = tokens[len(tokens) - 1].lower()

                if last_tok in ("sgt", "slt"):
                    new_tok = ""
                    if last_tok == "sgt":       # >
                        new_tok = "sge"         # >=
                    if last_tok == "slt":       # <
                        if child.text == "=":
                            new_tok = "sle"     # <=
                        elif child.text == ">":
                            new_tok = "ne"      # <>
                    tokens[len(tokens) - 1] = new_tok
                else:
                    tokens.append(cond_tokens[child.text.strip().upper()])

        elif tag == "classType":
            classType = "".join(t.text for t in child.findall("t"))
            if classType:
                tokens.append(classType.lower())

        elif tag == "t" and child.text in("(", ")"):
            tokens.append(child.text)

    return tokens

# ─────────────────────────────────────────────────────────────────────────────
#  Handler methods
# ─────────────────────────────────────────────────────────────────────────────
def handle_acceptStatement(elem):
    var = extractText(elem, "cobolWord")
    return { "ACCEPT": var }

def handle_dataDescriptionEntry(elem):
    name = extractText(elem, "cobolWord")
    string_literal =  extractText(elem, "alphanumericLiteral")
    integer_literal = extractText(elem, "integerLiteral")
    scope = extractText(elem, "levelNumber")

    if integer_literal.strip() == "":
        data = string_literal
    else:
        data = int(integer_literal)

    return { "PICTURE": [ name, data ] }

def handle_displayStatement(elem):
    '''
    Each display statement can have multiple arguments, which may include both
    variable identifiers and literal strings. The arguments of a display
    statement are passed as a list, where each element contains the name or
    value along with its type: 'var' for identifiers or 'lit' for literals.
    '''
    args = []
    literals_raw = extractText(elem, "alphanumericLiteral")
    idents = extractVarNames(elem, "identifier")

    literals = [s for _, s in re.findall(r"""(['"])(.*?)\1""", literals_raw)]

    for l in literals:
        args.append([l, "lit"])

    for i in idents:
        args.append([i, "var"])

    return { "DISPLAY": args }

def handle_ifStatement(elem):
    condition = extractConditionTokens(elem)

    then_block = []
    then_node = elem.find(".//thenBranch")
    if then_node is not None:
        then_block = process_node(then_node)

    else_block = []
    else_node = elem.find(".//elseBranch")
    if else_node is not None:
        else_block = process_node(else_node)

    return { "IF" : {
             "cond" : condition,
             "then" : then_block,
             "else" : else_block
            }
        }

def handle_moveStatement(elem):
    value = extractText(elem, "literalValue")
    var_name = extractText(elem, "cobolWord")
    return { "MOVE": [var_name, value] }

def handle_programIdParagraph(elem):
    return { "PROGRAM-ID": extractText(elem, "alphanumericConstant") }

def handle_setStatement(elem):
    var = extractText(elem, "cobolWord")
    # dodati u zavisnosti od tipa vrednosti.... tag za bool vrednosti je <true>
    val = extractText(elem, "true")
    return { "SET": [var, val] }

def handle_stopStatement(elem):
    return { "STOP": "RUN" }


# ─────────────────────────────────────────────────────────────────────────────
#  Handlers dictionary
# ─────────────────────────────────────────────────────────────────────────────
Handlers = {
    "acceptStatement" :         handle_acceptStatement,
    "dataDescriptionEntry" :    handle_dataDescriptionEntry,
    "displayStatement" :        handle_displayStatement,
    "ifStatement" :             handle_ifStatement,
    "moveStatement" :           handle_moveStatement,
    "programIdParagraph" :      handle_programIdParagraph,
    "setStatement" :            handle_setStatement,
    "stopStatement" :           handle_stopStatement
}
