"""
This file contains handlers for parsing the xml file generated by Koopa.
The xml tree is recursively traversed and recognized statements are processed
by their corresponding handlers, which return a structure representing the
statement and its associated data.
"""

import re

# ─────────────────────────────────────────────────────────────────────────────
#  Main processing
# ─────────────────────────────────────────────────────────────────────────────
# tags that manage their own children (if, for, while):
internal_recursion_tags = ["ifStatement", "evaluateStatement", "performStatement"]


def process_node(elem, ident=0, lines=None):
    if lines is None:
        lines = []

    handler = Handlers.get(elem.tag)
    if handler is not None:
        lines.append(handler(elem))

        if elem.tag in internal_recursion_tags:
            return lines

    for child in elem:
        process_node(child, ident + 1, lines)

    return lines


# ─────────────────────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────────────────────
# find all matching text
def extractText(elem, tag):
    return "".join(
        txt.text.strip()
        for cons in elem.findall(f".//{tag}")
        for txt in cons.findall(".//t")
        if txt.text
    )


def extractCompute(elem):
    text = "".join(t.text for t in elem.findall(".//t") if t.text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


# because koopa separates letters from nums in variable names...
def extractVarNames(elem, tag):
    vars = []
    for var in elem.findall(".//cobolWord"):
        var_name = "".join(t.text for t in var.findall("t"))
        vars.append(var_name)
    return vars


def extractConditionTokens(elem):
    node = elem.find(".//condition")
    tokens = []

    cond_tokens = {
        "<": "slt",
        "<=": "sle",
        ">": "sgt",
        ">=": "sge",
        "=": "eq",
        "<>": "ne",
        "IS": "is",
        "NOT": "not",
        "AND": "and",
        "OR": "or",
    }

    for child in node.iter():
        tag = child.tag

        if tag == "cobolWord":
            word = "".join(t.text for t in child.findall("t"))
            if word:
                tokens.append(word)

        elif tag == "integerLiteral":
            lit = "".join(t.text for t in child.findall("t"))
            if lit:
                tokens.append(("lit_int", int(lit)))

        elif tag == "numericLiteral":
            # numericLiteral may contain an integerLiteral child which we
            # already handled above — only add the value when no integer
            # child was found (e.g. a decimal literal).
            if child.find("integerLiteral") is None:
                lit = "".join(t.text for t in child.findall("t"))
                if lit:
                    try:
                        tokens.append(("lit_int", int(lit)))
                    except ValueError:
                        tokens.append(("lit_float", float(lit)))

        elif tag == "alphanumericLiteral":
            lit = "".join(t.text for t in child.findall("t"))
            if lit:
                tokens.append(("lit_str", lit.strip("'").strip('"')))

        elif tag == "t" and child.text.upper() in cond_tokens:
            if child.text and child.text.strip():
                """
                If the last op was a rela op, and the current tok is also a
                rela op, then they form the same op
                (e.g. if the last was < or >, and the current is = or >,
                this forms <=, >=, or <>).
                """
                last_tok_raw = tokens[-1] if tokens else None
                last_tok = last_tok_raw.lower() if isinstance(last_tok_raw, str) else ""

                if last_tok in ("sgt", "slt"):
                    new_tok = ""
                    if last_tok == "sgt":  # >
                        new_tok = "sge"  # >=
                    if last_tok == "slt":  # <
                        if child.text == "=":
                            new_tok = "sle"  # <=
                        elif child.text == ">":
                            new_tok = "ne"  # <>
                    tokens[len(tokens) - 1] = new_tok
                else:
                    tokens.append(cond_tokens[child.text.strip().upper()])

        elif tag == "classType":
            classType = "".join(t.text for t in child.findall("t"))
            if classType:
                tokens.append(classType.lower())

        elif tag == "t" and child.text in ("(", ")"):
            tokens.append(child.text)

    return tokens


# ─────────────────────────────────────────────────────────────────────────────
#  Handler methods
# ─────────────────────────────────────────────────────────────────────────────
def handle_acceptStatement(elem):
    var = extractText(elem, "cobolWord")
    return {"ACCEPT": var}


def handle_addStatement(elem):
    # to do: literals
    idents = extractVarNames(elem, "identifier")
    # first one: arg, second one: arg & res
    return {"ADD": idents}


def handle_computeStatement(elem):
    expression = re.findall(r"[A-Za-z_][A-Za-z0-9_]*|[()+\-*/=]", extractCompute(elem))
    return { "COMPUTE": expression }


def handle_dataDescriptionEntry(elem):
    name = extractText(elem, "cobolWord")
    string_literal = extractText(elem, "alphanumericLiteral")
    numeric_literal = extractText(elem, "numericLiteral")
    scope = extractText(elem, "levelNumber")

    length = 0

    # for floats:
    int_part = 0
    frac_part = 0

    # X(n), A(n), 9(n) or X, 99,...
    pictureString = extractText(elem, "pictureString")
    type = (
        "alpha"
        if pictureString.startswith("A")
        else (
            "alnum"
            if pictureString.startswith("X")
            else "float" if "V" in pictureString else "int"
        )
    )
    hasDef = pictureString.find("(") != -1
    if hasDef:
        if type == "int" or type == "alpha" or type == "alnum":
            length = int(pictureString.split("(")[1].split(")")[0])
        elif type == "float":
            int_part = int(pictureString.split("9(")[1].split(")")[0])
            frac_part = int(pictureString.split("V9(")[1].split(")")[0])
            length = 0
    else:
        # count chars:
        # to do ... float, string, int????
        length = len(pictureString)

    if pictureString == "":
        type = "struct"
        return {"STRUCT": {"name": name, "level": scope}}

    if numeric_literal.strip() == "":
        literal = string_literal
    elif type == "float":
        literal = float(numeric_literal)
    else:
        literal = int(numeric_literal)

    return {
        "PICTURE": {
            "name": name,
            "literal": literal,
            "type": type,
            "length": length,
            "level": scope,
            "int_part": int_part,
            "frac_part": frac_part,
        }
    }


def handle_displayStatement(elem):
    """
    Each display statement can have multiple arguments, which may include both
    variable identifiers and literal strings. The arguments of a display
    statement are passed as a list, where each element contains the name or
    value along with its type: 'var' for identifiers or 'lit' for literals.
    """
    args = []
    literals_raw = extractText(elem, "alphanumericLiteral")
    idents = extractVarNames(elem, "identifier")

    literals = [s for _, s in re.findall(r"""(['"])(.*?)\1""", literals_raw)]

    for l in literals:
        args.append([l, "lit"])

    for i in idents:
        args.append([i, "var"])

    return {"DISPLAY": args}


def handle_divideStatement(elem):
    idents = extractVarNames(elem, "identifier")
    # first one: arg, second one: arg & res
    return {"DIV": idents}


def handle_ifStatement(elem):
    condition = extractConditionTokens(elem)

    then_block = []
    then_node = elem.find("thenBranch")
    if then_node is not None:
        then_block = process_node(then_node)

    else_block = []
    else_node = elem.find("elseBranch")
    if else_node is not None:
        else_block = process_node(else_node)

    return {"IF": {"cond": condition, "then": then_block, "else": else_block}}


def handle_moveStatement(elem):
    value = extractText(elem, "literalValue")

    if not value:
        sendingOprnd = extractText(elem, "sending//identifier")
        allOprnds = extractText(elem, "identifier")
        receivingOprnd = allOprnds[len(allOprnds) - len(sendingOprnd) :]
        return {"MOVE": [receivingOprnd, sendingOprnd]}

    var_name = extractText(elem, "cobolWord")
    int_value = extractText(elem, "integerLiteral")
    str_value = extractText(elem, "alphanumericLiteral")
    value = int(int_value) if int_value else str_value.strip('"').strip("'")

    return {"MOVE": [var_name, value]}


def handle_multiplyStatement(elem):
    idents = extractVarNames(elem, "identifier")
    # first one: arg, second one: arg & res
    return {"MUL": idents}


def handle_performStatement(elem):
    """
    PERFORM n TIMES ... END-PERFORM
    Extracts iteration count and loop body statements.
    """
    # Get iteration count from integerLiteral
    times = 0
    for nl in elem.findall(".//integerLiteral"):
        txt = "".join(t.text for t in nl.findall("t"))
        if txt:
            times = int(txt)
            break

    if times == 0:
        # Try identifier for variable-based count
        for cw in elem.findall(".//cobolWord"):
            w = "".join(t.text for t in cw.findall("t"))
            if w:
                times = w  # will be looked up in symbol_table
                break

    # Extract loop body statements
    body_stmts = []
    for child in elem:
        if child.tag not in ("t",):
            sub_stmts = process_node(child)
            body_stmts.extend(sub_stmts)

    return {"PERFORM": {"times": times, "body": body_stmts}}


def handle_evaluateStatement(elem):
    """
    EVALUATE subject WHEN value1 stmts WHEN value2 stmts ... END-EVALUATE

    Koopa XML structure:
      <evaluateStatement>
        <subject><condition>...<identifier>GRADE</identifier>...</condition></subject>
        <when>
          <object><literal>...<integerLiteral>1</integerLiteral>...</literal></object>
          <nestedStatements>...statements...</nestedStatements>
        </when>
        ...
        <whenOther>
          <nestedStatements>...statements...</nestedStatements>
        </whenOther>
      </evaluateStatement>
    """
    # The subject is inside <subject> -> <condition> -> <identifier>
    subject_node = elem.find(".//subject")
    if subject_node is not None:
        ident = subject_node.find(".//identifier")
        if ident is not None:
            subject = "".join(t.text for t in ident.findall(".//t") if t.text)
        else:
            cw = subject_node.find(".//cobolWord")
            subject = "".join(t.text for t in cw.findall("t")) if cw is not None else ""
    else:
        subject = ""

    cases = []

    # Process each <when> branch (regular WHEN value cases)
    for when_node in elem.findall("when"):
        value = None

        # Extract value from <object> child
        obj = when_node.find("object")
        if obj is not None:
            # Try numeric literal
            nl = obj.find(".//integerLiteral")
            if nl is not None:
                num_txt = "".join(t.text for t in nl.findall("t"))
                if num_txt:
                    value = int(num_txt)
            if value is None:
                # Try float
                nl2 = obj.find(".//numericLiteral")
                if nl2 is not None and nl2.find("integerLiteral") is None:
                    num_txt = "".join(t.text for t in nl2.findall("t"))
                    if num_txt:
                        try:
                            value = int(num_txt)
                        except ValueError:
                            value = float(num_txt)
            if value is None:
                # Try alphanumeric literal
                al = obj.find(".//alphanumericLiteral")
                if al is not None:
                    str_txt = "".join(t.text for t in al.findall("t"))
                    if str_txt:
                        value = str_txt.strip("'").strip('"')

        # Extract statements from <nestedStatements>
        stmts = []
        nested = when_node.find("nestedStatements")
        if nested is not None:
            stmts = process_node(nested)

        cases.append({"value": value, "other": False, "stmts": stmts})

    # Process <whenOther> branch
    when_other = elem.find("whenOther")
    if when_other is not None:
        stmts = []
        nested = when_other.find("nestedStatements")
        if nested is not None:
            stmts = process_node(nested)
        cases.append({"value": None, "other": True, "stmts": stmts})

    return {"EVALUATE": {"subject": subject, "cases": cases}}


def handle_goToStatement(elem):
    target = ""
    for cw in elem.findall(".//cobolWord"):
        target = "".join(t.text for t in cw.findall("t"))
        break
    return {"GOTO": target}


def handle_paragraphName(elem):
    name = "".join(t.text for t in elem.findall(".//t") if t.text)
    return {"PARAGRAPH": name}


def handle_programIdParagraph(elem):
    return {"PROGRAM-ID": extractText(elem, "alphanumericConstant")}


def handle_setStatement(elem):
    var = extractText(elem, "cobolWord")
    # dodati u zavisnosti od tipa vrednosti.... tag za bool vrednosti je <true>
    val = extractText(elem, "true")
    return {"SET": [var, val]}


def handle_stopStatement(elem):
    return {"STOP": "RUN"}


def handle_subtractStatement(elem):
    # to do: literals
    idents = extractVarNames(elem, "identifier")
    # first one: arg, second one: arg & res
    return {"SUB": idents}


# ─────────────────────────────────────────────────────────────────────────────
#  Handlers dictionary
# ─────────────────────────────────────────────────────────────────────────────
Handlers = {
    "acceptStatement": handle_acceptStatement,
    "addStatement": handle_addStatement,
    "computeStatement": handle_computeStatement,
    "dataDescriptionEntry": handle_dataDescriptionEntry,
    "displayStatement": handle_displayStatement,
    "divideStatement": handle_divideStatement,
    "evaluateStatement": handle_evaluateStatement,
    "goToStatement": handle_goToStatement,
    "ifStatement": handle_ifStatement,
    "moveStatement": handle_moveStatement,
    "multiplyStatement": handle_multiplyStatement,
    "paragraphName": handle_paragraphName,
    "performStatement": handle_performStatement,
    "programIdParagraph": handle_programIdParagraph,
    "setStatement": handle_setStatement,
    "stopStatement": handle_stopStatement,
    "subtractStatement": handle_subtractStatement,
}
